---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-flux-webhooks
  namespace: flux-system
spec:
  path: ./kubernetes/apps/infrastructure/flux-system/addons/webhooks
  prune: true
  sourceRef:
    kind: GitRepository
    name: tlscert-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
