---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-network-ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-network-cert-manager
    - name: infra-network-cert-manager-issuers
  path: ./kubernetes/apps/infrastructure/network/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: tlscert-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: ingress-nginx
      namespace: network
  interval: 30m
  retryInterval: 1m
  timeout: 3m
