# This secret should be manually created in the cluster
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: network
type: Opaque
stringData:
  cloudflare_api_token: 'PLACEHOLDER'
