---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-network-cert-manager
  namespace: flux-system
spec:
  path: ./kubernetes/apps/infrastructure/network/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: tlscert-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cert-manager
      namespace: network
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-network-cert-manager-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-network-cert-manager
  path: ./kubernetes/apps/infrastructure/network/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: tlscert-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
