---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-network-external-dns
  namespace: flux-system
spec:
  path: ./kubernetes/apps/infrastructure/network/external-dns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: tlscert-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
