apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-tlscert-prod
  namespace: flux-system
spec:
  path: ./kubernetes/apps/tlscert/app
  dependsOn:
    - name: infra-flux-operator
    - name: infra-network-cert-manager
    - name: infra-network-cert-manager-issuers
    - name: infra-network-ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: tlscert-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m