apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: localhost.u.tlscert.dev
  namespace: tlscert
  labels:
    api.tlscert.dev/pool: manual
spec:
  dnsNames:
    - localhost.u.tlscert.dev
  secretName: localhost.u.tlscert.dev
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io