---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tlscert-kubernetes
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: main
  url: "https://github.com/tlscert/deployment.git"
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/kubernetes
    !/templates/kubernetes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: tlscert-kubernetes
