---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-flux-operator
  namespace: flux-system
spec:
  path: ./kubernetes/apps/infrastructure/flux-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: tlscert-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: flux-operator
      namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
